/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Bluetooth file transfer");
gchar *s = N_("<span weight=\"bold\" size=\"larger\">Sending file</span>");
gchar *s = N_("Choose destination device");
