/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("GNOME Bluetooth Device Viewer");
gchar *s = N_("Devices");
gchar *s = N_("Device details");
gchar *s = N_("Device services");
gchar *s = N_("Scan");
